/* G10-ADHESION V6.5 — 2026-10-02 */
(function(){
'use strict';
const V='6.5', TEST_WA='+1 778 808 2048', KEN='g10_wa_test_on_v65', KNUM='g10_wa_test_num_v65', KMAIL='g10_last_email_v65';
let uMembers=null,uPlatform=null,uSettings=null,uMember=null,page=1,pageSize=50,reconciling=false;
function d(v){return String(v||'').replace(/\D/g,'').replace(/^00/,'')}
function pk(v){var x=d(v);return x.length>=8?x.slice(-8):x}
function key(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function mname(m){return [m&&m.firstName,m&&m.firstName2,m&&m.lastName,m&&m.lastName2].filter(Boolean).join(' ').trim()}
function pname(p){return [p&&p.firstName,p&&p.firstName2,p&&p.lastName,p&&p.lastName2].filter(Boolean).join(' ').trim()||(p&&p.name)||''}
function mobile(){return matchMedia('(max-width:760px)').matches}
function testOn(){var v=localStorage.getItem(KEN);if(v===null){v='1';localStorage.setItem(KEN,v)}return v==='1'}
function testNum(){return localStorage.getItem(KNUM)||TEST_WA}
function official(){return String((settings&&settings.rtm)||(settings&&settings.airtel)||'+241 76 41 24 49').trim()}
function waDest(){return testOn()?testNum():official()}
function addStyle(){
 if(document.getElementById('g10v65css'))return;
 var s=document.createElement('style');s.id='g10v65css';s.textContent=
 '.g10-first-help{margin:8px 0 12px;padding:11px 12px;border:1px solid #b9d5ea;border-radius:12px;background:#f1f8fe;color:#24425f;font-size:12px;line-height:1.45}'+
 '.g10-test-active{font-weight:900!important;color:#087a48!important}.g10-step-progress{display:flex;justify-content:space-between;gap:10px;margin:10px 0;padding:11px 14px;border-radius:13px;background:#edf6fd;color:#225c89}.g10-step-toggle{display:none;margin-left:auto;border:0;background:#eef4f9;color:#0b4a7a;width:34px;height:34px;border-radius:50%;font-size:22px}'+
 '.g10-extbox{margin:12px 0;padding:12px 14px;border:1px solid #d9e5ef;border-radius:14px;background:#f8fbfe;display:flex;align-items:center;justify-content:space-between;gap:12px}.g10-extbox small{display:block;color:#65778c;margin-top:3px}.g10-modal{position:fixed;inset:0;z-index:12000;display:none;align-items:center;justify-content:center;padding:14px;background:rgba(8,35,58,.72)}.g10-modal.open{display:flex}.g10-dialog{position:relative;width:min(520px,100%);max-height:90dvh;overflow:auto;background:#fff;border-radius:20px;padding:22px}.g10-close{position:absolute;right:12px;top:12px;border:0;border-radius:50%;width:36px;height:36px;font-size:22px}.g10-service{width:100%;border:1px solid #dce5ef;border-radius:12px;background:#fff;padding:12px;margin:7px 0;display:flex;justify-content:space-between;color:#0b355a}'+
 '.g10-platform-tools,.g10-pager{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.g10-pager{justify-content:center;margin-top:12px}.g10-scroll{position:fixed;right:14px;bottom:18px;z-index:5000;display:grid;gap:7px}.g10-scroll button{width:42px;height:42px;border:1px solid #cddbea;border-radius:50%;background:#fff;color:#0b4a7a;font-size:20px;box-shadow:0 8px 20px rgba(8,35,58,.16)}.g10-menu{display:none}#directionApp .sidebar{overflow-y:auto}#directionApp .side-foot{position:static!important;margin-top:16px!important}'+
 '@media(max-width:760px){#directionApp{display:block!important}#directionApp.hidden{display:none!important}#directionApp .sidebar{position:fixed!important;left:0;top:0;width:min(84vw,310px)!important;height:100dvh!important;z-index:7000;transform:translateX(-105%);transition:.2s;overflow-y:auto!important}#directionApp.g10-open .sidebar{transform:translateX(0)}#directionApp .main{padding:66px 12px 95px!important}.g10-menu{display:flex;position:fixed;left:12px;top:max(10px,env(safe-area-inset-top));z-index:6900;border:0;border-radius:12px;padding:10px 13px;background:#0b4a7a;color:#fff;font-weight:900}.g10-step-toggle{display:block}.g10-step-card>.panel-head{cursor:pointer}.g10-step-card.g10-collapsed>:not(.panel-head){display:none!important}.g10-step-card{scroll-margin-top:70px}.g10-extbox{align-items:flex-start;flex-direction:column}.g10-extbox .btn{width:100%}.g10-platform-tools{width:100%;display:grid;grid-template-columns:1fr 1fr}.g10-pager .btn{padding:8px;font-size:11px}.g10-scroll{bottom:94px;right:10px}.g10-step-progress{position:sticky;top:8px;z-index:20}.g10-side-foot{position:static!important}}';
 document.head.appendChild(s);
}
function enhanceLogin(){
 var c=document.querySelector('.home-login-card'),e=document.getElementById('homeEmail'),p=document.getElementById('homePassword');if(!c||!e||!p)return;
 e.name='username';e.autocomplete='username';p.name='password';p.autocomplete='current-password';
 if(!e.value&&localStorage.getItem(KMAIL))e.value=localStorage.getItem(KMAIL);
 var bs=[].slice.call(c.querySelectorAll('.home-login-btn')),login=bs.find(function(b){return /se connecter/i.test(b.textContent||'')}),create=bs.find(function(b){return /cr.er/i.test(b.textContent||'')});
 if(create){create.textContent='Première connexion — Créer mon compte';if(login&&login.parentNode===create.parentNode)login.parentNode.insertBefore(create,login)}
 if(login)login.textContent='J’ai déjà un compte — Se connecter';
 if(!c.querySelector('.g10-first-help')){var h=document.createElement('div');h.className='g10-first-help';h.innerHTML='<b>Première connexion ?</b> Entrez votre courriel et choisissez un mot de passe, puis cliquez d’abord sur <b>Créer mon compte</b>. Utilisez Se connecter seulement si votre compte existe déjà.';var b=c.querySelector('.home-login-btn');if(b)c.insertBefore(h,b)}
}
window.loginFromHome=async function(){
 if(!auth){homeMessage('Firebase n’est pas disponible.',true);return}var email=normalizeEmail(val('homeEmail')),password=val('homePassword');if(!email||!password){homeMessage('Entrez votre adresse courriel et votre mot de passe.',true);return}
 try{if(firebase.auth.Auth&&firebase.auth.Auth.Persistence)await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);homeMessage('Connexion…');var cr=await auth.signInWithEmailAndPassword(email,password);localStorage.setItem(KMAIL,email);currentAuthUser=cr.user;currentUserRole=roleForEmail(cr.user.email||email);if(isPrivilegedRole()){await loadDirectionData();enterDirection()}else{await loadMemberFromFirebase(cr.user);enterMember()}}
 catch(err){var code=String(err&&err.code||'');if(/invalid-credential|wrong-password|user-not-found/.test(code))homeMessage('Compte introuvable ou mot de passe incorrect. Si c’est votre première connexion, cliquez sur « Créer mon compte ».',true);else homeMessage(firebaseErrorMessage(err),true)}
};
window.createAccountFromHome=async function(){
 if(!auth){homeMessage('Firebase n’est pas disponible.',true);return}var email=normalizeEmail(val('homeEmail')),password=val('homePassword');if(!email||!email.includes('@')){homeMessage('Entrez une adresse courriel valide.',true);return}if(password.length<6){homeMessage('Choisissez un mot de passe d’au moins 6 caractères.',true);return}
 try{if(firebase.auth.Auth&&firebase.auth.Auth.Persistence)await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);homeMessage('Création du compte…');var cr=await auth.createUserWithEmailAndPassword(email,password);localStorage.setItem(KMAIL,email);currentAuthUser=cr.user;currentUserRole=roleForEmail(email);currentMember=createMemberForEmail(email);currentMember.firebaseUid=cr.user.uid;currentMember.emailVerified=!!cr.user.emailVerified;await saveMemberToFirebase(currentMember);try{await cr.user.sendEmailVerification()}catch(e){}homeMessage('Compte créé. Vous pouvez maintenant compléter votre dossier.');enterMember()}catch(err){homeMessage(firebaseErrorMessage(err),true)}
};
function findMatch(m,emailOnly){
 var email=normalizeEmail(m&&m.email||''),ph=pk(m&&m.phone),fn=key(mname(m)),first=key(m&&m.firstName),a=[];
 platform.forEach(function(p,i){var pe=normalizeEmail(p.email||''),pp=pk(p.phone||p.telephone||p.whatsapp||''),pn=key(pname(p)),sc=0,r='';if(email&&pe&&email===pe){sc=100;r='courriel'}else if(!emailOnly&&ph&&pp&&ph===pp){sc=95;r='téléphone'}else if(!emailOnly&&fn&&pn&&fn===pn){sc=90;r='nom complet'}else if(!emailOnly&&first&&pn&&first===pn){sc=82;r='prénom / nom WhatsApp'}else if(!emailOnly&&fn&&pn&&fn.length>=5&&(fn.includes(pn)||pn.includes(fn))){sc=75;r='nom proche'}if(sc)a.push({index:i,score:sc,reason:r})});
 a.sort(function(x,y){return y.score-x.score});if(!a.length)return{index:-1};if(a.length>1&&a[0].score===a[1].score&&a[0].score<95)return{index:-1,ambiguous:true};return a[0]
}
window.findPlatformByEmail=function(email){return findMatch(currentMember?Object.assign({},currentMember,{email:email||currentMember.email}):{email:email},!currentMember).index};
async function updatePlatformFrom(m,status){
 var i=Number.isInteger(m.platformIndex)?m.platformIndex:findMatch(m,false).index;if(i<0||!platform[i])return -1;m.platformIndex=i;var p=platform[i];platform[i]=Object.assign({},p,{firstName:m.firstName||p.firstName||'',firstName2:m.firstName2||p.firstName2||'',lastName:m.lastName||p.lastName||'',lastName2:m.lastName2||p.lastName2||'',email:m.email||p.email||'',phone:m.phone||p.phone||'',country:m.country||p.country||'',profession:m.profession||p.profession||'',expertise:m.expertise||p.expertise||'',status:status||p.status||'Inactif',matchedMemberId:m.id||''});if(isPrivilegedRole())await savePlatformEntryToFirebase(i);return i
}
var oldSaveProfile=window.saveProfile;window.saveProfile=function(){oldSaveProfile();if(currentMember&&currentMember.profileComplete){var m=findMatch(currentMember,false);if(m.index>=0){currentMember.platformIndex=m.index;currentMember.platformMatchStatus='Rapproché automatiquement — '+m.reason;saveMemberToFirebase(currentMember).catch(console.error)}stepUi(true)}};
async function proof(file){
 if(!file)return null;var t=String(file.type||'');if(t==='application/pdf'){if(file.size>450000)throw new Error('PDF trop volumineux : maximum 450 Ko, sinon utilisez une capture.');var x=await new Promise(function(ok,no){var r=new FileReader();r.onload=function(){ok(r.result)};r.onerror=no;r.readAsDataURL(file)});return{data:x,name:file.name,type:t}}
 if(!t.startsWith('image/'))throw new Error('Formats acceptés : JPG, PNG ou PDF.');var src=await new Promise(function(ok,no){var r=new FileReader();r.onload=function(){ok(r.result)};r.onerror=no;r.readAsDataURL(file)}),im=await new Promise(function(ok,no){var i=new Image();i.onload=function(){ok(i)};i.onerror=no;i.src=src}),scale=Math.min(1,900/Math.max(im.width,im.height)),w=Math.round(im.width*scale),h=Math.round(im.height*scale);
 function enc(q,W,H){var c=document.createElement('canvas');c.width=W;c.height=H;var z=c.getContext('2d');z.fillStyle='#fff';z.fillRect(0,0,W,H);z.drawImage(im,0,0,W,H);return c.toDataURL('image/jpeg',q)}var data=enc(.5,w,h);if(data.length>220000){scale=Math.min(1,650/Math.max(im.width,im.height));w=Math.round(im.width*scale);h=Math.round(im.height*scale);data=enc(.4,w,h)}if(data.length>300000)throw new Error('Capture trop volumineuse. Recadrez le reçu.');return{data:data,name:file.name,type:'image/jpeg'}
}
function openProof(p){if(!p||!p.data){alert('Aucun justificatif.');return}var w=window.open('','_blank');if(!w)return;if(p.type==='application/pdf')w.document.write('<iframe src="'+p.data+'" style="border:0;width:100vw;height:100vh"></iframe>');else w.document.write('<body style="margin:0;background:#111;display:grid;place-items:center;min-height:100vh"><img src="'+p.data+'" style="max-width:96vw;max-height:96vh"></body>');w.document.close()}
window.g10Proof=function(id){var m=applications.find(function(a){return a.id===id})||activeMembers.find(function(a){return a.id===id});openProof(m&&m.paymentProofData)};
window.declarePayment=async function(){
 if(!currentMember||!currentMember.formSigned){alert('Validez d’abord la fiche et la signature.');return}if(!val('transactionRef')||!val('paymentDate')){alert('Indiquez la référence et la date.');return}var i=document.getElementById('paymentProof'),f=i&&i.files&&i.files[0];if(!f){alert('Joignez votre justificatif : capture/photo ou PDF.');return}
 try{currentMember.transactionRef=val('transactionRef');currentMember.paymentDate=val('paymentDate');currentMember.paymentMethod=(document.querySelector('input[name=payMethod]:checked')||{}).value||'Airtel Money';currentMember.paymentProofData=await proof(f);currentMember.paymentDeclared=true;currentMember.status='Paiement déclaré — contrôle Direction';upsertApplication();syncMemberEverywhere(currentMember);persist();await saveMemberToFirebase(currentMember);hydrateMember();refreshDirection();stepUi(true);alert('Paiement déclaré avec justificatif. La Direction doit maintenant le vérifier.')}catch(e){alert(e.message||'Impossible de préparer le justificatif.')}
};
window.sendWhatsAppPayment=function(){
 if(!currentMember)return alert('Ouvrez d’abord votre dossier.');var ref=val('transactionRef')||currentMember.transactionRef||'à renseigner',date=val('paymentDate')||currentMember.paymentDate||'à renseigner',name=mname(currentMember)||currentMember.email||'Adhérent',dest=waDest();
 var msg='Bonjour Direction G10, je confirme mon paiement du droit d’adhésion.\nNom : '+name+'\nDossier : '+currentMember.id+'\nMontant : '+settings.membershipFee+' €\nRTM Money officiel : '+official()+'\nRéférence transaction : '+ref+'\nDate : '+date+'\nLe justificatif est joint dans mon dossier G10. Merci de vérifier et valider mon adhésion.';window.open('https://wa.me/'+d(dest)+'?text='+encodeURIComponent(msg),'_blank','noopener')
};
function testUi(){var e=document.getElementById('paymentDestination');if(e){e.textContent='RTM Money officiel : '+official()+(testOn()?'  •  WhatsApp TEST : '+testNum():'');e.classList.toggle('g10-test-active',testOn())}document.querySelectorAll('.whatsapp-btn').forEach(function(b){b.textContent=testOn()?'Envoyer la confirmation sur WhatsApp TEST ('+testNum()+')':'Envoyer la confirmation sur WhatsApp'})}
function cards(){return [].slice.call(document.querySelectorAll('#member-account > .card.panel')).filter(function(c){var h=c.querySelector('.panel-head h3');return h&&/^[123]\./.test((h.textContent||'').trim())})}
function markCards(){cards().forEach(function(c,i){c.classList.add('g10-step-card');var h=c.querySelector('.panel-head');if(h&&!h.querySelector('.g10-step-toggle')){var b=document.createElement('button');b.type='button';b.className='g10-step-toggle';b.textContent='⌄';h.appendChild(b);h.addEventListener('click',function(ev){if(!mobile())return;if(ev.target.closest('button')&&!ev.target.classList.contains('g10-step-toggle'))return;c.classList.toggle('g10-collapsed');b.textContent=c.classList.contains('g10-collapsed')?'›':'⌄'})}});if(!document.getElementById('g10StepProgress')){var w=document.querySelector('#member-account > .card.panel'),x=document.createElement('div');x.id='g10StepProgress';x.className='g10-step-progress';if(w)w.insertAdjacentElement('afterend',x)}}
function curStep(){if(!currentMember||!currentMember.profileComplete)return 1;if(!currentMember.formSigned)return 2;return 3}
function stepUi(scroll){markCards();var cs=cards(),st=curStep(),p=document.getElementById('g10StepProgress');if(p)p.innerHTML='<b>Étape '+st+' sur 3</b><span>'+(['','Identité et coordonnées','Fiche & signature','Droit d’adhésion'][st])+'</span>';if(mobile())cs.forEach(function(c,i){var done=(i===0&&currentMember&&currentMember.profileComplete)||(i===1&&currentMember&&currentMember.formSigned)||(i===2&&currentMember&&currentMember.paymentConfirmed),open=(i+1===st&&!done);c.classList.toggle('g10-collapsed',!open);var b=c.querySelector('.g10-step-toggle');if(b)b.textContent=c.classList.contains('g10-collapsed')?'›':'⌄'});else cs.forEach(function(c){c.classList.remove('g10-collapsed')});if(scroll&&mobile()&&cs[st-1])setTimeout(function(){cs[st-1].scrollIntoView({behavior:'smooth',block:'start'})},100)}
var oldSmart=window.validateSmartForm;window.validateSmartForm=function(){oldSmart();stepUi(true)};
function services(){if(!Array.isArray(settings.externalPaymentServices)||!settings.externalPaymentServices.length)settings.externalPaymentServices=[{name:'LemFi',url:'https://lemfi.com/',active:true},{name:'E-Billing',url:'https://ebilling-pay.com/',active:true}];return settings.externalPaymentServices}
function payModal(){if(document.getElementById('g10PayModal'))return;var m=document.createElement('div');m.id='g10PayModal';m.className='g10-modal';m.innerHTML='<div class="g10-dialog"><button class="g10-close">×</button><h3>Ouvrir un service de paiement</h3><p class="muted">Le paiement se fait hors de G10. Revenez ensuite joindre votre justificatif.</p><div id="g10ServiceList"></div><p class="muted">Un service absent peut être proposé à la Direction depuis votre dossier lors d’une prochaine mise à jour.</p></div>';document.body.appendChild(m);m.querySelector('.g10-close').onclick=function(){m.classList.remove('open')};m.onclick=function(e){if(e.target===m)m.classList.remove('open')}}
function extBox(){var f=document.getElementById('membershipPaymentForm');if(!f||document.getElementById('g10ExtBox'))return;var hi=f.querySelector('.payment-highlight');if(!hi)return;var b=document.createElement('div');b.id='g10ExtBox';b.className='g10-extbox';b.innerHTML='<div><b>Option 2 — ouvrir un service de paiement externe</b><small>Facultatif. Effectuez le paiement sur votre service habituel puis revenez joindre la preuve.</small></div><button type="button" class="btn btn-light">Choisir un service</button>';hi.insertAdjacentElement('afterend',b);b.querySelector('button').onclick=function(){payModal();var l=document.getElementById('g10ServiceList');l.innerHTML=services().filter(function(s){return s.active!==false&&s.url}).map(function(s){return '<button class="g10-service" data-u="'+esc(s.url)+'"><b>'+esc(s.name)+'</b><span>Ouvrir ↗</span></button>'}).join('');l.querySelectorAll('[data-u]').forEach(function(x){x.onclick=function(){window.open(x.dataset.u,'_blank','noopener')}});document.getElementById('g10PayModal').classList.add('open')}}
function settingsExt(){
 var sec=document.getElementById('dir-settings'),h=sec&&sec.querySelector('.card.panel');if(!h||document.getElementById('g10V65Settings'))return;var b=document.createElement('div');b.id='g10V65Settings';b.innerHTML='<div class="sep"></div><h3>Mode démonstration WhatsApp</h3><div class="form-grid"><div class="field"><label>Activer WhatsApp TEST</label><select id="g10TestOn"><option value="1">Oui — TEST</option><option value="0">Non — officiel</option></select></div><div class="field"><label>Numéro WhatsApp TEST</label><input id="g10TestNum" type="tel"></div></div><div class="action-row"><button class="btn btn-primary" id="g10SaveTest">Enregistrer le mode TEST</button></div><div class="sep"></div><h3>Services de paiement externes</h3><div id="g10ServiceAdmin"></div><div class="form-grid"><div class="field"><label>Nom du service</label><input id="g10SrvName"></div><div class="field"><label>Lien https://</label><input id="g10SrvUrl" type="url"></div></div><div class="action-row"><button class="btn btn-light" id="g10AddSrv">Ajouter le service</button></div>';h.appendChild(b);document.getElementById('g10TestOn').value=testOn()?'1':'0';document.getElementById('g10TestNum').value=testNum();document.getElementById('g10SaveTest').onclick=function(){localStorage.setItem(KEN,document.getElementById('g10TestOn').value);localStorage.setItem(KNUM,document.getElementById('g10TestNum').value.trim()||TEST_WA);testUi();alert('Mode TEST enregistré sur cet appareil.')};document.getElementById('g10AddSrv').onclick=async function(){var n=document.getElementById('g10SrvName').value.trim(),u=document.getElementById('g10SrvUrl').value.trim();if(!n||!/^https?:\/\//i.test(u)){alert('Nom et lien https:// requis.');return}services().push({name:n,url:u,active:true});await saveSettingsToFirebase();renderSrv();document.getElementById('g10SrvName').value='';document.getElementById('g10SrvUrl').value=''};renderSrv()
}
window.g10RemoveSrv=async function(i){settings.externalPaymentServices=services().filter(function(s,j){return j!==i});await saveSettingsToFirebase();renderSrv()};
function renderSrv(){var x=document.getElementById('g10ServiceAdmin');if(x)x.innerHTML=services().map(function(s,i){return '<div style="display:flex;justify-content:space-between;gap:8px;border:1px solid #dce5ef;border-radius:10px;padding:9px;margin:6px 0"><span><b>'+esc(s.name)+'</b><br><small>'+esc(s.url)+'</small></span><button class="btn btn-light" onclick="g10RemoveSrv('+i+')">Retirer</button></div>'}).join('')}
function navFix(){var app=document.getElementById('directionApp');if(!app)return;if(!document.getElementById('g10Menu')){var b=document.createElement('button');b.id='g10Menu';b.className='g10-menu';b.innerHTML='☰ Menu';b.onclick=function(){app.classList.toggle('g10-open')};document.body.appendChild(b)}var sb=app.querySelector('.sidebar');if(sb&&!sb.dataset.v65){sb.dataset.v65='1';sb.addEventListener('click',function(e){if(mobile()&&e.target.closest('.navbtn'))app.classList.remove('g10-open')})}if(!document.getElementById('g10Scroll')){var n=document.createElement('div');n.id='g10Scroll';n.className='g10-scroll';n.innerHTML='<button>↑</button><button>↓</button>';n.children[0].onclick=function(){scrollTo({top:0,behavior:'smooth'})};n.children[1].onclick=function(){scrollTo({top:document.documentElement.scrollHeight,behavior:'smooth'})};document.body.appendChild(n)}}
function platformTools(){var s=document.getElementById('dir-platform'),t=s&&s.querySelector('.toolbar');if(!t||document.getElementById('g10Tools'))return;var w=document.createElement('div');w.id='g10Tools';w.className='g10-platform-tools';w.innerHTML='<select id="g10Status"><option value="">Tous les statuts</option><option>Inactif</option><option>Inscrit</option><option>Adhérent</option><option>Actif</option></select><select id="g10Size"><option>25</option><option selected>50</option><option>100</option></select><button class="btn btn-light" id="g10Csv">Exporter CSV</button><button class="btn btn-light" id="g10Xls">Exporter Excel</button>';t.appendChild(w);document.getElementById('g10Status').onchange=function(){page=1;renderPlatform()};document.getElementById('g10Size').onchange=function(e){pageSize=Number(e.target.value);page=1;renderPlatform()};document.getElementById('g10Csv').onclick=exportBase;document.getElementById('g10Xls').onclick=exportXls;var tr=s.querySelector('thead tr');if(tr)tr.innerHTML='<th>N°</th><th>Nom</th><th>Contact</th><th>Pays</th><th>Profession / expertise</th><th>Statut</th><th>Action</th>';var p=document.createElement('div');p.id='g10Pager';p.className='g10-pager';s.querySelector('.table-wrap').insertAdjacentElement('afterend',p)}
function filt(){var q=key((document.getElementById('platformSearch')||{}).value||''),st=String((document.getElementById('g10Status')||{}).value||'').toLowerCase();return platform.map(function(p,i){return Object.assign({},p,{i:i})}).filter(function(p){return(!q||key(JSON.stringify(p)).includes(q))&&(!st||String(p.status||'Inactif').toLowerCase().startsWith(st))})}
window.renderPlatform=function(){platformTools();var b=document.getElementById('platformRows');if(!b)return;var r=filt(),pages=Math.max(1,Math.ceil(r.length/pageSize));if(page>pages)page=pages;var start=(page-1)*pageSize,sh=r.slice(start,start+pageSize);b.innerHTML=sh.length?sh.map(function(p,j){var c=String(p.status||'').toLowerCase(),cl=c==='actif'?'badge-ok':c==='adhérent'?'badge-info':c==='inscrit'?'badge-warn':'badge-off';return '<tr><td>'+(start+j+1)+'</td><td><b>'+esc(pname(p)||'—')+'</b></td><td>'+esc(p.email||p.phone||'—')+'</td><td>'+esc(p.country||'—')+'</td><td>'+esc(p.profession||p.expertise||'—')+'</td><td><span class="badge '+cl+'">'+esc(p.status||'Inactif')+'</span></td><td><button class="btn btn-light" onclick="enterMemberFromPlatform('+p.i+')">Ouvrir dossier</button></td></tr>'}).join(''):'<tr><td colspan="7">Aucun membre correspondant.</td></tr>';var p=document.getElementById('g10Pager');if(p){p.innerHTML='<button class="btn btn-light" data-p="first">«</button><button class="btn btn-light" data-p="prev">‹</button><b>Page '+page+' / '+pages+' — '+r.length+' membres</b><button class="btn btn-light" data-p="next">›</button><button class="btn btn-light" data-p="last">»</button>';p.querySelectorAll('[data-p]').forEach(function(x){x.onclick=function(){var a=x.dataset.p;if(a==='first')page=1;if(a==='prev')page=Math.max(1,page-1);if(a==='next')page=Math.min(pages,page+1);if(a==='last')page=pages;renderPlatform()}})}}
function rows(){return[['N°','Nom','Prénom 1','Prénom 2','Adresse courriel','Téléphone / WhatsApp','Pays','Profession','Expertise','Statut']].concat(platform.map(function(p,i){return[i+1,p.lastName||p.name||'',p.firstName||'',p.firstName2||'',p.email||'',p.phone||'',p.country||'',p.profession||'',p.expertise||'',p.status||'Inactif']}))}
function exportBase(){downloadCSV('G10_base_plateforme_'+new Date().toISOString().slice(0,10)+'.csv',rows())}
function exportXls(){var rs=rows(),html='<html><meta charset="utf-8"><table border="1">'+rs.map(function(r,i){return'<tr>'+r.map(function(v){return(i?'<td>':'<th>')+esc(v)+(i?'</td>':'</th>')}).join('')+'</tr>'}).join('')+'</table></html>',blob=new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='G10_base_plateforme_'+new Date().toISOString().slice(0,10)+'.xls';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},700)}
async function reconcile(){if(reconciling||!db||!isPrivilegedRole()||!platform.length)return;reconciling=true;try{for(var z=0;z<applications.length;z++){var m=applications[z];if(!m.profileComplete||!m.firebaseUid)continue;var i=Number.isInteger(m.platformIndex)?m.platformIndex:findMatch(m,false).index;if(i<0||!platform[i])continue;var sum=typeof contributionSummary==='function'?contributionSummary(m):null,status=(sum&&sum.plan&&sum.confirmed>=sum.max)?'Actif':(m.paymentConfirmed||m.active)?'Adhérent':'Inscrit';var changed=m.platformIndex!==i||platform[i].email!==m.email||platform[i].phone!==m.phone||platform[i].status!==status;if(changed){m.platformIndex=i;m.platformMatchStatus='Rapproché automatiquement';platform[i]=Object.assign({},platform[i],{firstName:m.firstName||platform[i].firstName||'',firstName2:m.firstName2||platform[i].firstName2||'',lastName:m.lastName||platform[i].lastName||'',lastName2:m.lastName2||platform[i].lastName2||'',email:m.email||platform[i].email||'',phone:m.phone||platform[i].phone||'',country:m.country||platform[i].country||'',profession:m.profession||platform[i].profession||'',expertise:m.expertise||platform[i].expertise||'',status:status,matchedMemberId:m.id||''});await savePlatformEntryToFirebase(i);await db.collection('members').doc(m.firebaseUid).set({platformIndex:i,platformMatchStatus:m.platformMatchStatus,updatedAt:new Date().toISOString()},{merge:true})}}}catch(e){console.warn(e)}reconciling=false}
function stop(){[uMembers,uPlatform,uSettings,uMember].forEach(function(f){try{if(typeof f==='function')f()}catch(e){}});uMembers=uPlatform=uSettings=uMember=null}
function dirRT(){if(!db||!isPrivilegedRole())return;uMembers=db.collection('members').onSnapshot(function(s){applications=s.docs.map(function(x){return Object.assign({},x.data(),{firebaseUid:x.id})});activeMembers=applications.filter(function(a){return a.active});refreshDirection();setTimeout(reconcile,80)});uPlatform=db.collection('platform').orderBy('order').onSnapshot(function(s){platform=s.docs.map(function(x){return Object.assign({},x.data(),{firebaseDocId:x.id})});refreshDirection();refreshLanding();setTimeout(reconcile,80)});uSettings=db.collection('settings').doc('public').onSnapshot(function(s){if(s.exists){settings=Object.assign({},settings,s.data());localStorage.setItem('g10_settings_v2',JSON.stringify(settings));hydrateSettings();refreshLanding();refreshDirection();renderSrv()}})}
function memRT(){if(!db||!currentAuthUser||isPrivilegedRole())return;uMember=db.collection('members').doc(currentAuthUser.uid).onSnapshot(function(s){if(s.exists){currentMember=Object.assign({},s.data(),{firebaseUid:currentAuthUser.uid,email:s.data().email||currentAuthUser.email||'',emailVerified:!!currentAuthUser.emailVerified});hydrateMember();stepUi(false)}})}
var oldEnterD=window.enterDirection;window.enterDirection=function(){oldEnterD();navFix();platformTools();settingsExt();dirRT()};
var oldEnterM=window.enterMember;window.enterMember=function(){oldEnterM();extBox();payModal();memRT();stepUi(false);testUi()};
var oldGo=window.goHome;window.goHome=async function(){stop();return oldGo()};
var oldHyd=window.hydrateMember;window.hydrateMember=function(){oldHyd();extBox();testUi();stepUi(false)};
window.renderApplications=function(){var p=applications.filter(function(a){return !a.active}),c=document.getElementById('appCount'),b=document.getElementById('applicationRows');if(c)c.textContent=p.length+' dossier'+(p.length>1?'s':'');if(!b)return;b.innerHTML=p.length?p.map(function(a){var pr=(a.paymentProofData&&a.paymentProofData.data)?'<br><button class="btn btn-light" onclick="g10Proof(\''+esc(a.id)+'\')">Voir justificatif</button>':'',can=a.profileComplete&&a.formSigned&&a.paymentDeclared&&a.paymentProofData&&a.paymentProofData.data;return'<tr><td><b>'+esc(a.id)+'</b></td><td>'+esc(mname(a)||'À compléter')+'<br><small>'+esc(a.email||'')+'</small></td><td>'+(a.profileComplete?'<span class="badge badge-ok">OK</span>':'<span class="badge badge-warn">À compléter</span>')+'</td><td>'+(a.formSigned?'<span class="badge badge-ok">Signée</span>':'<span class="badge badge-warn">À signer</span>')+'</td><td>'+(a.paymentDeclared?'<span class="badge badge-warn">À vérifier</span>':'<span class="badge badge-off">Non déclaré</span>')+pr+'</td><td>'+esc(a.expertise||a.profession||'—')+'</td><td><button class="btn btn-green" '+(!can?'disabled':'')+' onclick="validateApplication(\''+esc(a.id)+'\')">Valider adhésion</button></td></tr>'}).join(''):'<tr><td colspan="7">Aucun dossier en attente.</td></tr>'};
window.validateApplication=async function(id){var i=applications.findIndex(function(a){return a.id===id});if(i<0)return;var a=applications[i];if(!a.profileComplete||!a.formSigned||!a.paymentDeclared||!a.paymentProofData||!a.paymentProofData.data){alert('Profil, fiche signée, déclaration et justificatif requis.');return}a.paymentConfirmed=true;a.active=true;a.status='Adhérent';a.membershipValidatedAt=new Date().toISOString();applications[i]=a;var ai=activeMembers.findIndex(function(x){return x.id===id});if(ai>=0)activeMembers[ai]=JSON.parse(JSON.stringify(a));else activeMembers.push(JSON.parse(JSON.stringify(a)));await updatePlatformFrom(a,'Adhérent');if(currentMember&&currentMember.id===id)currentMember=JSON.parse(JSON.stringify(a));persist();try{await saveAnyMemberToFirebase(a)}catch(e){}refreshDirection();alert('Adhésion validée : statut « Adhérent ». Le statut « Actif » sera atteint lorsque la cotisation sera à jour.')};
var oldConfirm=window.confirmContributionPayment;if(typeof oldConfirm==='function')window.confirmContributionPayment=function(mid,pid){oldConfirm(mid,pid);setTimeout(async function(){var m=applications.find(function(a){return a.id===mid})||activeMembers.find(function(a){return a.id===mid}),s=m&&typeof contributionSummary==='function'?contributionSummary(m):null;if(m&&s&&s.plan&&s.confirmed>=s.max){await updatePlatformFrom(m,'Actif');renderPlatform()}},250)};
function init(){addStyle();enhanceLogin();navFix();platformTools();markCards();extBox();payModal();settingsExt();testUi();if(auth&&firebase.auth.Auth&&firebase.auth.Auth.Persistence)auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(function(){});addEventListener('resize',function(){stepUi(false)});console.info('G10 Adhésion V'+V+' chargé')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();